services:
  frontend:
    build: 
      context: .
      dockerfile: ./dockerfiles/dockerfile.frontend.dev
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/dockerfile.backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules